import BaloTibi from '../../../images/balo_tibi_3.png';

export const products = [
    {
        id: 1,
        name: "Balo Tibi Xanh",
        image: BaloTibi,
        cost: 150000,
        category: "Tibi",
        gender: "Boy",
        discount: "",
    },
    {
        id: 2,
        name: "Balo Laptop 1",
        image: BaloTibi,
        cost: 200000,
        category: "Laptop",
        gender: "Boy",
        discount: "",
    },
    {
        id: 3,
        name: "Balo Tiểu học 1",
        image: BaloTibi,
        cost: 300000,
        category: "Tiểu học",
        gender: "Boy",
        discount: "",
    },
    {
        id: 4,
        name: "Balo Tibi Đỏ",
        image: BaloTibi,
        cost: 400000,
        category: "Tibi",
        gender: "Girl",
        discount: 45,
    },
    {
        id: 5,
        name: "Balo Laptop 2",
        image: BaloTibi,
        cost: 150000,
        category: "Laptop",
        gender: "Girl",
        discount: "",
    },
    {
        id: 6,
        name: "Balo Tiểu học 2",
        image: BaloTibi,
        cost: 200000,
        category: "Tiểu học",
        gender: "Girl",
        discount: "",
    },
    {
        id: 7,
        name: "Balo Tibi Vàng",
        image: BaloTibi,
        cost: 300000,
        category: "Tibi",
        gender: "Girl",
        discount: "",
    },
    {
        id: 8,
        name: "Balo Laptop 3",
        image: BaloTibi,
        cost: 400000,
        category: "Laptop",
        gender: "Boy",
        discount: 50,
    },
    {
        id: 9,
        name: "Balo Tibi Xanh",
        image: BaloTibi,
        cost: 150000,
        category: "Tibi",
        gender: "Boy",
        discount: "",
    },
    {
        id: 10,
        name: "Balo Laptop 1",
        image: BaloTibi,
        cost: 200000,
        category: "Laptop",
        gender: "Boy",
        discount: "",
    },
    {
        id: 11,
        name: "Balo Tiểu học 1",
        image: BaloTibi,
        cost: 300000,
        category: "Tiểu học",
        gender: "Boy",
        discount: "",
    },
    {
        id: 12,
        name: "Balo Tibi Đỏ",
        image: BaloTibi,
        cost: 400000,
        category: "Tibi",
        gender: "Girl",
        discount: 45,
    },
    {
        id: 13,
        name: "Balo Laptop 2",
        image: BaloTibi,
        cost: 150000,
        category: "Laptop",
        gender: "Girl",
        discount: "",
    },
    {
        id: 14,
        name: "Balo Tiểu học 2",
        image: BaloTibi,
        cost: 200000,
        category: "Tiểu học",
        gender: "Girl",
        discount: "",
    },
    {
        id: 15,
        name: "Balo Tibi Vàng",
        image: BaloTibi,
        cost: 300000,
        category: "Tibi",
        gender: "Girl",
        discount: "",
    },
    {
        id: 16,
        name: "Balo Laptop 3",
        image: BaloTibi,
        cost: 400000,
        category: "Laptop",
        gender: "Boy",
        discount: 50,
    },
    
]
